/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Inventario;

import Clases.Auxiliares.BusquedasBaseDatos;
import Clases.Auxiliares.NoEditableTableModel;
import Clases.Auxiliares.RenderHeader;
import Clases.Datos.Proveedor;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author JoBren8
 */
public class JdlgProveedorModificar extends javax.swing.JDialog {

    //Variables
    NoEditableTableModel modeloProveedores;

    public JdlgProveedorModificar(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        //Asignamos el nuevo Render del Header para que los titulos estan centrados
        jtblProveedores.getTableHeader().setDefaultRenderer(new RenderHeader(jtblProveedores));
        inicializarDatos();
    }

    private void inicializarDatos() {
        //Creamos un nuevo modelo
        modeloProveedores = new NoEditableTableModel();

        //Asignamos el modelo a la tabla
        jtblProveedores.setModel(modeloProveedores);

        // Creamos las columnas.
        modeloProveedores.addColumn("Código");
        modeloProveedores.addColumn("Nombre del Proveedor");
        modeloProveedores.addColumn("Teléfono");


        //PROVEEDORES
        try {
            //Se obtiene el ResultSet con los proveedores
            ResultSet rs = BusquedasBaseDatos.buscarProveedores();

            //Llenamos el modelo de la tabla
            Object[] filaTabla = new Object[3];
            while (rs.next()) {
                filaTabla[0] = rs.getObject(1);
                filaTabla[1] = rs.getObject(2);
                filaTabla[2] = rs.getObject(3);
                modeloProveedores.addRow(filaTabla);
            }
            //Cerramos la conexion
            BusquedasBaseDatos.cerrar();
        } catch (Exception ex) {
        }
    }

    private boolean validarCampos() {
        //NOMBRE PROVEEDOR - OBLIGATORIO
        if (jtxtNombreProveedor.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre del proveedor, no puede estar vacío!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            jtxtNombreProveedor.requestFocus();
            return false;
        } else if (jtxtNombreProveedor.getText().length() > 500) {
            JOptionPane.showMessageDialog(this, "El nombre del proveedor, no puede ser mayor a 500 carácteres!",
                    "Verifique", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //TELEFONO
        if (jtxtTelefono.getText().length() > 15) {
            JOptionPane.showMessageDialog(this, "El teléfono, no puede ser mayor a 15 carácteres!",
                    "Verifique", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlPrincipal = new VistaJPanelConFondo.JPanelConFondo();
        jpnlTitulo = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jpnlContenedorDatos = new javax.swing.JPanel();
        jlblTituloCodigo = new javax.swing.JLabel();
        jtxtCodigo = new javax.swing.JTextField();
        jlblTituloNombreProveedor = new javax.swing.JLabel();
        jtxtNombreProveedor = new javax.swing.JTextField();
        jlblTituloTelefono = new javax.swing.JLabel();
        jtxtTelefono = new javax.swing.JTextField();
        jbtnModificar = new javax.swing.JButton();
        jspnProveedores = new javax.swing.JScrollPane();
        jtblProveedores = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Modificar Proveedor");

        jpnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarProveedor32x32.png"))); // NOI18N
        jlblTitulo.setText("Modificar Proveedor");
        jpnlTitulo.add(jlblTitulo);

        jpnlContenedorDatos.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblTituloCodigo.setText("Código:");

        jtxtCodigo.setToolTipText("Código del Proveedor");
        jtxtCodigo.setEnabled(false);

        jlblTituloNombreProveedor.setText("Nombre del Proveedor:");

        jtxtNombreProveedor.setToolTipText("Nombre del proveedor");

        jlblTituloTelefono.setText("Teléfono:");

        jtxtTelefono.setToolTipText("Teléfono de referencia del proveedor");

        jbtnModificar.setText("Modificar");
        jbtnModificar.setToolTipText("Modificar los datos del proveedor");
        jbtnModificar.setNextFocusableComponent(jtxtNombreProveedor);
        jbtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlContenedorDatosLayout = new javax.swing.GroupLayout(jpnlContenedorDatos);
        jpnlContenedorDatos.setLayout(jpnlContenedorDatosLayout);
        jpnlContenedorDatosLayout.setHorizontalGroup(
            jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlContenedorDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlContenedorDatosLayout.createSequentialGroup()
                        .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblTituloNombreProveedor)
                            .addComponent(jlblTituloCodigo)
                            .addComponent(jlblTituloTelefono))
                        .addGap(18, 18, 18)
                        .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContenedorDatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnModificar)))
                .addContainerGap())
        );
        jpnlContenedorDatosLayout.setVerticalGroup(
            jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlContenedorDatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloCodigo)
                    .addComponent(jtxtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloNombreProveedor)
                    .addComponent(jtxtNombreProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlContenedorDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloTelefono)
                    .addComponent(jtxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtnModificar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jspnProveedores.setToolTipText("Proveedores existentes en el sistema");

        jtblProveedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtblProveedores.setToolTipText("Proveedores existentes en el sistema");
        jtblProveedores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtblProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblProveedoresMouseClicked(evt);
            }
        });
        jspnProveedores.setViewportView(jtblProveedores);

        javax.swing.GroupLayout jpnlPrincipalLayout = new javax.swing.GroupLayout(jpnlPrincipal);
        jpnlPrincipal.setLayout(jpnlPrincipalLayout);
        jpnlPrincipalLayout.setHorizontalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnlContenedorDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jspnProveedores))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpnlPrincipalLayout.setVerticalGroup(
            jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jpnlContenedorDatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jspnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(jpnlPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlPrincipalLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(453, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtblProveedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblProveedoresMouseClicked
        int fila = jtblProveedores.rowAtPoint(evt.getPoint());
        int columna = jtblProveedores.columnAtPoint(evt.getPoint());
        if ((fila > -1) && (columna > -1)) {
            jtxtCodigo.setText(jtblProveedores.getModel().getValueAt(fila, 0).toString());
            jtxtNombreProveedor.setText(jtblProveedores.getModel().getValueAt(fila, 1).toString());
            jtxtTelefono.setText(jtblProveedores.getModel().getValueAt(fila, 2).toString());
        }
    }//GEN-LAST:event_jtblProveedoresMouseClicked

    private void jbtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarActionPerformed
        if (validarCampos()) {
            Proveedor proveedor = new Proveedor();
            proveedor.setIdProveedor(Integer.parseInt(jtxtCodigo.getText()));
            proveedor.setNombreProveedor(jtxtNombreProveedor.getText());
            proveedor.setTelefono(jtxtTelefono.getText());
            if (proveedor.modificarProveedor()) {
                JOptionPane.showMessageDialog(this, "Proveedor modificado!", "Listo!",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se ha podido modificar el proveedor", "Uuupppsss!",
                        JOptionPane.ERROR_MESSAGE);
            }
            inicializarDatos();
        }
    }//GEN-LAST:event_jbtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgProveedorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgProveedorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgProveedorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgProveedorModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdlgProveedorModificar dialog = new JdlgProveedorModificar(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnModificar;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTituloCodigo;
    private javax.swing.JLabel jlblTituloNombreProveedor;
    private javax.swing.JLabel jlblTituloTelefono;
    private javax.swing.JPanel jpnlContenedorDatos;
    private VistaJPanelConFondo.JPanelConFondo jpnlPrincipal;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JScrollPane jspnProveedores;
    private javax.swing.JTable jtblProveedores;
    private javax.swing.JTextField jtxtCodigo;
    private javax.swing.JTextField jtxtNombreProveedor;
    private javax.swing.JTextField jtxtTelefono;
    // End of variables declaration//GEN-END:variables
}
