/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Inventario;

import Clases.Auxiliares.*;
import Clases.Datos.Movimiento;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author jobren8
 */
public class JdlgAsignarCheque extends javax.swing.JDialog {

    //Variables
    NoEditableTableModel modeloMovimientos;
    boolean confirmarPermiso = false; //Nos indicara si la accion a ejecutar tiene permiso

    public JdlgAsignarCheque(java.awt.Frame parent, boolean modal, String encargado) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        //USUARIO
        jtxtEncargado.setText(encargado);
        inicializarDatos();
    }

    private void inicializarDatos() {

        //TABLA DE MOVIMIENTOS
        //Creamos la instancia del modelo
        modeloMovimientos = new NoEditableTableModel();
        jtblMovimientosSinCheque.setModel(modeloMovimientos);

        //Creamos las columnas del modelo
        modeloMovimientos.addColumn("Movimiento");
        modeloMovimientos.addColumn("Factura");
        modeloMovimientos.addColumn("Proveedor");
        modeloMovimientos.addColumn("Monto");
        modeloMovimientos.addColumn("Asignar");

        //Numeramos la columna que es editable
        modeloMovimientos.setColumnaEditable(4);

        JCheckBox checkBox = new javax.swing.JCheckBox();
        jtblMovimientosSinCheque.getColumn("Asignar").setCellEditor(new DefaultCellEditor(checkBox));

        //Asignamos el nuevo Render del Header para que los titulos estan centrados
        jtblMovimientosSinCheque.getTableHeader().setDefaultRenderer(new RenderHeader(jtblMovimientosSinCheque));
        //Se crea el JCheckBox en la columna indicada en getColumn, en este caso, la primera columna
        jtblMovimientosSinCheque.getColumnModel().getColumn(4).setCellEditor(new CeldaCheckBox());
        //Para pintar la columna con el CheckBox en la tabla, en este caso, la primera columna
        jtblMovimientosSinCheque.getColumnModel().getColumn(4).setCellRenderer(new RenderCheckBox());

        //MOVIMIENTOS SIN CHEQUE
        try {
            //Se obtiene el ResultSet con los movimientos sin cheque
            ResultSet rs = BusquedasBaseDatos.buscarMovimientosSinCheque();

            //Llenamos el modelo de la tabla
            Object[] filaTabla = new Object[5];
            while (rs.next()) {
                filaTabla[0] = rs.getObject(1);
                filaTabla[1] = rs.getObject(2);
                filaTabla[2] = rs.getObject(3);
                filaTabla[3] = rs.getObject(4);
                filaTabla[4] = false;
                modeloMovimientos.addRow(filaTabla);
            }
            //Cerramos la conexion
            BusquedasBaseDatos.cerrar();

        } catch (Exception ex) {
        }
    }

    private boolean validarCampos() {
        //NUMERO CHEQUE - OBLIGATORIO
        if (jtxtNumeroCheque.getText().trim().equals("")) {
            JOptionPane.showMessageDialog(this, "El numero de cheque, no puede estar vacío!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            jtxtNumeroCheque.requestFocus();
            return false;
        } else if (jtxtNumeroCheque.getText().length() > 30) {
            JOptionPane.showMessageDialog(this, "El numero de cheque, no puede ser mayor a 30 carácteres!",
                    "Verifique", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        return true;
    }

    public void setConfirmarPermiso(boolean permiso) {
        this.confirmarPermiso = permiso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlAsignarCheque = new VistaJPanelConFondo.JPanelConFondo();
        jpnlTitulo = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jpnlDatosCheque = new javax.swing.JPanel();
        jlblTituloNumeroCheque = new javax.swing.JLabel();
        jtxtNumeroCheque = new javax.swing.JTextField();
        jbtnAsignar = new javax.swing.JButton();
        jlblTituloEncargado = new javax.swing.JLabel();
        jtxtEncargado = new javax.swing.JTextField();
        jscpMovimientosSinCheque = new javax.swing.JScrollPane();
        jtblMovimientosSinCheque = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Asignar Cheque");

        jpnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCheque32x32.png"))); // NOI18N
        jlblTitulo.setText("Asignar Cheque");
        jpnlTitulo.add(jlblTitulo);

        jpnlDatosCheque.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jlblTituloNumeroCheque.setText("Numero de Cheque:");

        jtxtNumeroCheque.setToolTipText("Número de cheque con que se realiza el pago de las facturas");

        jbtnAsignar.setText("Asignar");
        jbtnAsignar.setToolTipText("Aplica la asignación del numero de cheque");
        jbtnAsignar.setNextFocusableComponent(jtxtNumeroCheque);
        jbtnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAsignarActionPerformed(evt);
            }
        });

        jlblTituloEncargado.setText("Encargado:");

        jtxtEncargado.setToolTipText("");
        jtxtEncargado.setEnabled(false);

        javax.swing.GroupLayout jpnlDatosChequeLayout = new javax.swing.GroupLayout(jpnlDatosCheque);
        jpnlDatosCheque.setLayout(jpnlDatosChequeLayout);
        jpnlDatosChequeLayout.setHorizontalGroup(
            jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTituloNumeroCheque)
                    .addComponent(jlblTituloEncargado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtEncargado, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addComponent(jtxtNumeroCheque))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbtnAsignar)
                .addContainerGap())
        );
        jpnlDatosChequeLayout.setVerticalGroup(
            jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloNumeroCheque)
                    .addComponent(jtxtNumeroCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDatosChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jlblTituloEncargado)
                        .addComponent(jtxtEncargado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbtnAsignar))
                .addContainerGap())
        );

        jscpMovimientosSinCheque.setToolTipText("Facturas sin numero de cheque");

        jtblMovimientosSinCheque.setAutoCreateRowSorter(true);
        jtblMovimientosSinCheque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Movimiento", "Numero Factura", "Proveedor", "Monto", "Asignar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblMovimientosSinCheque.setToolTipText("Facturas sin numero de cheque");
        jscpMovimientosSinCheque.setViewportView(jtblMovimientosSinCheque);

        javax.swing.GroupLayout jpnlAsignarChequeLayout = new javax.swing.GroupLayout(jpnlAsignarCheque);
        jpnlAsignarCheque.setLayout(jpnlAsignarChequeLayout);
        jpnlAsignarChequeLayout.setHorizontalGroup(
            jpnlAsignarChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAsignarChequeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlAsignarChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnlDatosCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jscpMovimientosSinCheque, javax.swing.GroupLayout.DEFAULT_SIZE, 485, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jpnlAsignarChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlAsignarChequeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpnlAsignarChequeLayout.setVerticalGroup(
            jpnlAsignarChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlAsignarChequeLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jpnlDatosCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jscpMovimientosSinCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlAsignarChequeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlAsignarChequeLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlAsignarCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlAsignarCheque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAsignarActionPerformed
        if (validarCampos()) {
            JdlgConfirmarPermiso ventanaConfirmar = new JdlgConfirmarPermiso(this, true,
                    jtxtEncargado.getText());
            ventanaConfirmar.setVisible(true);

            boolean vacio = true;
            ArrayList<String> movimientos = new ArrayList();
            if (confirmarPermiso) {
                //Recorremos el modelo para ver los movimientos seleccionados
                for (int x = 0; x < modeloMovimientos.getRowCount(); x++) {
                    if (modeloMovimientos.getValueAt(x, 4).equals(true)) {
                        movimientos.add(modeloMovimientos.getValueAt(x, 0).toString() + "-"
                                + modeloMovimientos.getValueAt(x, 1).toString());
                        vacio = false;
                    }
                }

                //Verificamos que existe al menos una linea seleccionada
                if (!vacio) {
                    Movimiento mov = new Movimiento();
                    if (mov.asignarCheque(movimientos, jtxtNumeroCheque.getText())) {
                        JOptionPane.showMessageDialog(this, "Cheque asignado con éxito!",
                                "Listo", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error. \nNo se ha podido asignar el cheque.",
                                "Uppsss!", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna linea!",
                            "Verifique", JOptionPane.ERROR_MESSAGE);
                }
            }
            confirmarPermiso = false;
        }
    }//GEN-LAST:event_jbtnAsignarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgAsignarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgAsignarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgAsignarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgAsignarCheque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdlgAsignarCheque dialog = new JdlgAsignarCheque(new javax.swing.JFrame(), true, "");
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnAsignar;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTituloEncargado;
    private javax.swing.JLabel jlblTituloNumeroCheque;
    private VistaJPanelConFondo.JPanelConFondo jpnlAsignarCheque;
    private javax.swing.JPanel jpnlDatosCheque;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JScrollPane jscpMovimientosSinCheque;
    private javax.swing.JTable jtblMovimientosSinCheque;
    private javax.swing.JTextField jtxtEncargado;
    private javax.swing.JTextField jtxtNumeroCheque;
    // End of variables declaration//GEN-END:variables
}
