/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administracion;

import Clases.Auxiliares.BusquedasBaseDatos;
import Clases.Auxiliares.HelpMethods;
import Clases.Datos.Usuario;
import Interfaz.Inventario.JdlgConfirmarPermiso;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author jbrenesbl
 */
public class JdlgCrearUsuario extends javax.swing.JDialog {

    //Variables
    Usuario usuarioActual = new Usuario();
    ArrayList<String> usuarios = new ArrayList();
    boolean confirmarPermiso = false;

   public JdlgCrearUsuario(java.awt.Frame parent, boolean modal, Usuario user) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.usuarioActual = user;
        inicializarDatos();
    }

    private void inicializarDatos() {
        ResultSet rs = BusquedasBaseDatos.buscarUsuarios();
        try {
            while (rs.next()) {
                usuarios.add(rs.getObject(1).toString());
            }
            BusquedasBaseDatos.cerrar();
        } catch (Exception ex) {
            BusquedasBaseDatos.cerrar();
        }
    }

    private boolean validarCampos() {
        //NOMBRE USUARIO
        //No Vacio
        if (!jtxtNombreUsuario.getText().trim().equals("")) {
            //Largo del Campo
            if (jtxtNombreUsuario.getText().trim().length() <= 50) {
                //Caracteres Alfanumericos
                if (HelpMethods.isAlfanumerico(jtxtNombreUsuario.getText().trim())) {
                    //Disponible
                    for (int x = 0; x < usuarios.size(); x++) {
                        if (jtxtNombreUsuario.getText().trim().equals(usuarios.get(x))) {
                            JOptionPane.showMessageDialog(this, "El Nombre de Usuario, no está disponible!",
                                    "Verifique", JOptionPane.ERROR_MESSAGE);
                            return false;
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El campo Nombre de Usuario, debe contener solamente letras o números!",
                            "Verifique", JOptionPane.ERROR_MESSAGE);
                    return false;
                }
            } else {
                JOptionPane.showMessageDialog(this, "El campo Nombre de Usuario, no puede ser mayor a 50 carácteres!",
                        "Verifique", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo Nombre de Usuario, no puede esta vacío!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //PASSWORD
        //No Vacio
        if (jtxtPassword.getPassword().length > 0) {
            //Largo del Campo
            if (jtxtPassword.getPassword().length > 50) {
                JOptionPane.showMessageDialog(this, "El campo Contraseña, no puede ser mayor a 50 carácteres!",
                        "Verifique", JOptionPane.ERROR_MESSAGE);
                return false;
            }
        } else {
            JOptionPane.showMessageDialog(this, "El campo Contraseña, no puede esta vacío!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //CONFIRMAR PASSWORD
        //Password igual
        if (!Arrays.equals(jtxtPassword.getPassword(), jtxtConfirmacionPassword.getPassword())) {
            JOptionPane.showMessageDialog(this, "El campo Confirmación Contraseña, "
                    + "no coincide con la contraseña digitada anteriormente!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //Si todo esta bien
        return true;
    }

    public void setConfirmarPermiso(boolean permiso) {
        this.confirmarPermiso = permiso;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCrearUsuario = new VistaJPanelConFondo.JPanelConFondo();
        jpnlTitulo = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jpnlDatosUsuario = new VistaJPanelConFondo.JPanelConFondo();
        jlblTituloNombreUsuario = new javax.swing.JLabel();
        jtxtNombreUsuario = new javax.swing.JTextField();
        jlblTituloPassword = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jlblTituloConfirmacionPassword = new javax.swing.JLabel();
        jtxtConfirmacionPassword = new javax.swing.JPasswordField();
        jlblTituloRol = new javax.swing.JLabel();
        jcbxRol = new javax.swing.JComboBox();
        jbtnCrear = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlTitulo.setLayout(new java.awt.GridLayout(1, 0));

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("Crear Usuario");
        jpnlTitulo.add(jlblTitulo);

        jpnlDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Usuario"));

        jlblTituloNombreUsuario.setText("Nombre de Usuario:");

        jtxtNombreUsuario.setToolTipText("Nombre de Usuario del Sistema");

        jlblTituloPassword.setText("Contraseña:");

        jtxtPassword.setToolTipText("Contraseña del Usuario");

        jlblTituloConfirmacionPassword.setText("Confirmación Contraseña:");

        jtxtConfirmacionPassword.setToolTipText("Contraseña del Usuario");

        jlblTituloRol.setText("Rol:");

        jcbxRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        javax.swing.GroupLayout jpnlDatosUsuarioLayout = new javax.swing.GroupLayout(jpnlDatosUsuario);
        jpnlDatosUsuario.setLayout(jpnlDatosUsuarioLayout);
        jpnlDatosUsuarioLayout.setHorizontalGroup(
            jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTituloNombreUsuario)
                    .addComponent(jlblTituloPassword)
                    .addComponent(jlblTituloConfirmacionPassword)
                    .addComponent(jlblTituloRol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtConfirmacionPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombreUsuario))
                        .addContainerGap())
                    .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(145, Short.MAX_VALUE))))
        );
        jpnlDatosUsuarioLayout.setVerticalGroup(
            jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloNombreUsuario)
                    .addComponent(jtxtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloPassword)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloConfirmacionPassword)
                    .addComponent(jtxtConfirmacionPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloRol)
                    .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnCrear.setText("Crear");
        jbtnCrear.setPreferredSize(new java.awt.Dimension(75, 23));
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlCrearUsuarioLayout = new javax.swing.GroupLayout(jpnlCrearUsuario);
        jpnlCrearUsuario.setLayout(jpnlCrearUsuarioLayout);
        jpnlCrearUsuarioLayout.setHorizontalGroup(
            jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar))
                    .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jpnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpnlCrearUsuarioLayout.setVerticalGroup(
            jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jpnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        if (validarCampos()) {
            if (usuarioActual.getRol().equals("Admin")) {
                JdlgConfirmarPermiso ventanaConfirmar = new JdlgConfirmarPermiso(this, true,
                        usuarioActual.getUsuario());
                ventanaConfirmar.setVisible(true);

                if (confirmarPermiso) {
                    //Creamos el objeto y seteamos los valores
                    Usuario user = new Usuario();
                    user.setUsuario(jtxtNombreUsuario.getText());
                    user.setRol(jcbxRol.getSelectedItem().toString());
                    //Invocamos el metodo de agregar pasandole el parametro de la contraseña
                    if (user.insertarUsuario(jtxtPassword.getPassword())) {
                        JOptionPane.showMessageDialog(this, "Usuario " + user.getUsuario() + ", creado con éxito!",
                                "Usuario creado", JOptionPane.INFORMATION_MESSAGE);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Ha ocurrido un error. \nNo se ha podido crear el usuario.",
                                "Uppsss!", JOptionPane.ERROR_MESSAGE);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No tiene privilegios para esta acción!",
                        "Acceso Denegado", JOptionPane.WARNING_MESSAGE);
                this.dispose();
            }
            confirmarPermiso = false;
        }
    }//GEN-LAST:event_jbtnCrearActionPerformed

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdlgCrearUsuario dialog = new JdlgCrearUsuario(new javax.swing.JFrame(), true, new Usuario());
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JComboBox jcbxRol;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTituloConfirmacionPassword;
    private javax.swing.JLabel jlblTituloNombreUsuario;
    private javax.swing.JLabel jlblTituloPassword;
    private javax.swing.JLabel jlblTituloRol;
    private VistaJPanelConFondo.JPanelConFondo jpnlCrearUsuario;
    private VistaJPanelConFondo.JPanelConFondo jpnlDatosUsuario;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JPasswordField jtxtConfirmacionPassword;
    private javax.swing.JTextField jtxtNombreUsuario;
    private javax.swing.JPasswordField jtxtPassword;
    // End of variables declaration//GEN-END:variables
}
