/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz.Administracion;

/**
 *
 * @author jbrenesbl
 */
public class JdlgCrearUsuario extends javax.swing.JDialog {

    /**
     * Creates new form JdlgCrearUsuario
     */
    public JdlgCrearUsuario(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlCrearUsuario = new VistaJPanelConFondo.JPanelConFondo();
        jpnlTitulo = new javax.swing.JPanel();
        jlblTitulo = new javax.swing.JLabel();
        jpnlDatosUsuario = new VistaJPanelConFondo.JPanelConFondo();
        jlblTituloNombreUsuario = new javax.swing.JLabel();
        jtxtNombreUsuario = new javax.swing.JTextField();
        jlblTituloPassword = new javax.swing.JLabel();
        jtxtPassword = new javax.swing.JPasswordField();
        jlblTituloConfirmacionPassword = new javax.swing.JLabel();
        jtxtConfirmacionPassword = new javax.swing.JPasswordField();
        jlblPasswordCorrecto = new javax.swing.JLabel();
        jlblTituloRol = new javax.swing.JLabel();
        jcbxRol = new javax.swing.JComboBox();
        jbtnCrear = new javax.swing.JButton();
        jbtnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlTitulo.setLayout(new java.awt.GridLayout());

        jlblTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblTitulo.setText("Crear Usuario");
        jpnlTitulo.add(jlblTitulo);

        jpnlDatosUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Usuario"));

        jlblTituloNombreUsuario.setText("Nombre de Usuario:");

        jtxtNombreUsuario.setToolTipText("Nombre de Usuario del Sistema");

        jlblTituloPassword.setText("Contraseña:");

        jtxtPassword.setToolTipText("Contraseña del Usuario");

        jlblTituloConfirmacionPassword.setText("Confirmación Contraseña:");

        jtxtConfirmacionPassword.setToolTipText("Contraseña del Usuario");

        jlblPasswordCorrecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblPasswordCorrecto.setText("T");

        jlblTituloRol.setText("Rol:");

        jcbxRol.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "User" }));

        javax.swing.GroupLayout jpnlDatosUsuarioLayout = new javax.swing.GroupLayout(jpnlDatosUsuario);
        jpnlDatosUsuario.setLayout(jpnlDatosUsuarioLayout);
        jpnlDatosUsuarioLayout.setHorizontalGroup(
            jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlblTituloNombreUsuario)
                    .addComponent(jlblTituloPassword)
                    .addComponent(jlblTituloConfirmacionPassword)
                    .addComponent(jlblTituloRol))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                        .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jtxtConfirmacionPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(jtxtPassword, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtNombreUsuario))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlblPasswordCorrecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                        .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(162, Short.MAX_VALUE))))
        );
        jpnlDatosUsuarioLayout.setVerticalGroup(
            jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloNombreUsuario)
                    .addComponent(jtxtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloPassword)
                    .addComponent(jtxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloConfirmacionPassword)
                    .addComponent(jtxtConfirmacionPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlblPasswordCorrecto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblTituloRol)
                    .addComponent(jcbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnCrear.setText("Crear");
        jbtnCrear.setPreferredSize(new java.awt.Dimension(75, 23));
        jbtnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearActionPerformed(evt);
            }
        });

        jbtnCancelar.setText("Cancelar");

        javax.swing.GroupLayout jpnlCrearUsuarioLayout = new javax.swing.GroupLayout(jpnlCrearUsuario);
        jpnlCrearUsuario.setLayout(jpnlCrearUsuarioLayout);
        jpnlCrearUsuarioLayout.setHorizontalGroup(
            jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                        .addComponent(jpnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlCrearUsuarioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnCancelar)))
                .addContainerGap())
            .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jpnlCrearUsuarioLayout.setVerticalGroup(
            jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jpnlDatosUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnCancelar)
                    .addComponent(jbtnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jpnlCrearUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpnlCrearUsuarioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(216, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCrearUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlCrearUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnCrearActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgCrearUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdlgCrearUsuario dialog = new JdlgCrearUsuario(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnCrear;
    private javax.swing.JComboBox jcbxRol;
    private javax.swing.JLabel jlblPasswordCorrecto;
    private javax.swing.JLabel jlblTitulo;
    private javax.swing.JLabel jlblTituloConfirmacionPassword;
    private javax.swing.JLabel jlblTituloNombreUsuario;
    private javax.swing.JLabel jlblTituloPassword;
    private javax.swing.JLabel jlblTituloRol;
    private VistaJPanelConFondo.JPanelConFondo jpnlCrearUsuario;
    private VistaJPanelConFondo.JPanelConFondo jpnlDatosUsuario;
    private javax.swing.JPanel jpnlTitulo;
    private javax.swing.JPasswordField jtxtConfirmacionPassword;
    private javax.swing.JTextField jtxtNombreUsuario;
    private javax.swing.JPasswordField jtxtPassword;
    // End of variables declaration//GEN-END:variables
}
