package Interfaz.Reportes;

import Clases.Auxiliares.Reportes;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author jobren8
 */
public class JdlgReporteProductoHistorico extends javax.swing.JDialog {

    //Variables
    String condicionSQL = "WHERE ";

    public JdlgReporteProductoHistorico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null); //Centrar la ventana
        jckbFechaMovimiento.setSelected(false);
    }

    private boolean validarCampos() {
        //Validar que al menos una condicion se marque
        if (jckbTipoMovimiento.isSelected() | jckbFechaMovimiento.isSelected()) {
           
            //RANGO DE FECHAS            
            //No Vacías
            if (jckbFechaMovimiento.isSelected()) {
                if (jdchFechaMovimientoInicial.getDate() != null & jdchFechaMovimientoFinal.getDate() != null) {
                    //Fecha Inicio menor que Fecha Final
                    if (jdchFechaMovimientoInicial.getDate().after(jdchFechaMovimientoFinal.getDate())) {
                        JOptionPane.showMessageDialog(this, "La fecha inicio no puede ser mayor a la fecha final!",
                                "Verifique", JOptionPane.INFORMATION_MESSAGE);
                        return false;
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No se ha seleccionado ambas fechas!", "Verifique",
                            JOptionPane.INFORMATION_MESSAGE);
                    jdchFechaMovimientoInicial.requestFocus();
                    return false;
                }
            }            
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ningún criterio de filtrado!", "Verifique",
                    JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }

    private void creaCondicion() {
        //Borramos los datos anteriores
        condicionSQL = "WHERE ";
        
        //TIPO MOVIMIENTO
        if (jckbTipoMovimiento.isSelected()) {
            if (jrbtEntrada.isSelected()) {
                condicionSQL += "movimientos.Tipo = 'Entrada' AND ";
            } else {
                condicionSQL += "movimientos.Tipo = 'Salida' AND ";
            }
        }

        //RANGO FECHAS
        if (jckbFechaMovimiento.isSelected()) {
            String fechaInicio = jdchFechaMovimientoInicial.getCalendar().get(Calendar.YEAR) + "-"
                    + (jdchFechaMovimientoInicial.getCalendar().get(Calendar.MONTH) + 1) + "-"
                    + jdchFechaMovimientoInicial.getCalendar().get(Calendar.DATE);
            String fechaFin = jdchFechaMovimientoFinal.getCalendar().get(Calendar.YEAR) + "-"
                    + (jdchFechaMovimientoFinal.getCalendar().get(Calendar.MONTH) + 1) + "-"
                    + jdchFechaMovimientoFinal.getCalendar().get(Calendar.DATE);
            condicionSQL += "(movimientos.FechaMovimiento >= '" + fechaInicio + "' AND "
                    + "movimientos.FechaMovimiento <= '" + fechaFin + "') AND ";
        }
        
        //Quitamos el "AND " del final de la sentencia
        condicionSQL = condicionSQL.substring(0, condicionSQL.length() - 4);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbtgTipoMovimiento = new javax.swing.ButtonGroup();
        jpnlContenedorTotal = new VistaJPanelConFondo.JPanelConFondo();
        jpnlDatosBuscar = new javax.swing.JPanel();
        jckbTipoMovimiento = new javax.swing.JCheckBox();
        jrbtEntrada = new javax.swing.JRadioButton();
        jrbtSalida = new javax.swing.JRadioButton();
        jckbFechaMovimiento = new javax.swing.JCheckBox();
        jdchFechaMovimientoInicial = new com.toedter.calendar.JDateChooser();
        jlblHastaFecha = new javax.swing.JLabel();
        jdchFechaMovimientoFinal = new com.toedter.calendar.JDateChooser();
        jbtnBuscarMovimientos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte Histórico de Productos");
        setResizable(false);

        jpnlDatosBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder("Parámetros"));

        jckbTipoMovimiento.setText("Tipo de Movimiento:");

        jbtgTipoMovimiento.add(jrbtEntrada);
        jrbtEntrada.setSelected(true);
        jrbtEntrada.setText("Entrada");
        jrbtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtEntradaActionPerformed(evt);
            }
        });

        jbtgTipoMovimiento.add(jrbtSalida);
        jrbtSalida.setText("Salida");
        jrbtSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbtSalidaActionPerformed(evt);
            }
        });

        jckbFechaMovimiento.setText("Fecha Movimiento:");

        jdchFechaMovimientoInicial.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdchFechaMovimientoInicialPropertyChange(evt);
            }
        });

        jlblHastaFecha.setText("hasta");

        jdchFechaMovimientoFinal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jdchFechaMovimientoFinalPropertyChange(evt);
            }
        });

        jbtnBuscarMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBuscarProducto32x32.png"))); // NOI18N
        jbtnBuscarMovimientos.setToolTipText("Buscar productos según filtro");
        jbtnBuscarMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarMovimientosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlDatosBuscarLayout = new javax.swing.GroupLayout(jpnlDatosBuscar);
        jpnlDatosBuscar.setLayout(jpnlDatosBuscarLayout);
        jpnlDatosBuscarLayout.setHorizontalGroup(
            jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                .addGroup(jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jckbTipoMovimiento)
                    .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jrbtEntrada)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jrbtSalida)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                .addComponent(jckbFechaMovimiento)
                .addGap(12, 12, 12)
                .addGroup(jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                        .addComponent(jdchFechaMovimientoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlblHastaFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jdchFechaMovimientoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jbtnBuscarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jpnlDatosBuscarLayout.setVerticalGroup(
            jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                .addGroup(jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbtEntrada)
                    .addComponent(jrbtSalida)
                    .addComponent(jckbTipoMovimiento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jckbFechaMovimiento)
                    .addComponent(jdchFechaMovimientoInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnlDatosBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlblHastaFecha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jdchFechaMovimientoFinal, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jpnlDatosBuscarLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jbtnBuscarMovimientos, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnlContenedorTotalLayout = new javax.swing.GroupLayout(jpnlContenedorTotal);
        jpnlContenedorTotal.setLayout(jpnlContenedorTotalLayout);
        jpnlContenedorTotalLayout.setHorizontalGroup(
            jpnlContenedorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContenedorTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnlDatosBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnlContenedorTotalLayout.setVerticalGroup(
            jpnlContenedorTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlContenedorTotalLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jpnlDatosBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlContenedorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlContenedorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtEntradaActionPerformed
        jckbTipoMovimiento.setSelected(true);
    }//GEN-LAST:event_jrbtEntradaActionPerformed

    private void jrbtSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbtSalidaActionPerformed
        jckbTipoMovimiento.setSelected(true);
    }//GEN-LAST:event_jrbtSalidaActionPerformed

    private void jdchFechaMovimientoInicialPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdchFechaMovimientoInicialPropertyChange
        jckbFechaMovimiento.setSelected(true);
        jdchFechaMovimientoFinal.requestFocus();
    }//GEN-LAST:event_jdchFechaMovimientoInicialPropertyChange

    private void jdchFechaMovimientoFinalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jdchFechaMovimientoFinalPropertyChange
        jckbFechaMovimiento.setSelected(true);
    }//GEN-LAST:event_jdchFechaMovimientoFinalPropertyChange

    private void jbtnBuscarMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarMovimientosActionPerformed
        if (validarCampos()) {
            creaCondicion();
            Reportes reporte = new Reportes();
            if (!reporte.reporteProductoHistorico(condicionSQL)) {
                JOptionPane.showMessageDialog(this, "No seha podido mostrar el reporte!", 
                        "Uuupppsss!", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jbtnBuscarMovimientosActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;


                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdlgReporteProductoHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdlgReporteProductoHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdlgReporteProductoHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdlgReporteProductoHistorico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdlgReporteProductoHistorico dialog = new JdlgReporteProductoHistorico(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup jbtgTipoMovimiento;
    private javax.swing.JButton jbtnBuscarMovimientos;
    private javax.swing.JCheckBox jckbFechaMovimiento;
    private javax.swing.JCheckBox jckbTipoMovimiento;
    private com.toedter.calendar.JDateChooser jdchFechaMovimientoFinal;
    private com.toedter.calendar.JDateChooser jdchFechaMovimientoInicial;
    private javax.swing.JLabel jlblHastaFecha;
    private VistaJPanelConFondo.JPanelConFondo jpnlContenedorTotal;
    private javax.swing.JPanel jpnlDatosBuscar;
    private javax.swing.JRadioButton jrbtEntrada;
    private javax.swing.JRadioButton jrbtSalida;
    // End of variables declaration//GEN-END:variables
}
