/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Clases.Datos.Usuario;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author JoBren8
 */
public class JfrmPrincipal extends javax.swing.JFrame {

    //Variables
    Usuario usuarioActual = new Usuario();
    
    public JfrmPrincipal(Usuario usuario) {
        aplicaAspecto();
        initComponents();        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null); //Centrar la ventana
        this.usuarioActual = usuario;
        jlblUsuario.setText(usuario.getUsuario());
    }

    private void aplicaAspecto() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        } catch (Exception e) {
        }
    }
    
    public Usuario getUsuarioActual()
    {
        return this.usuarioActual;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlFondo = new VistaJPanelConFondo.JPanelConFondo();
        jpnlBarraEstado = new javax.swing.JPanel();
        jlblTituloUsuario = new javax.swing.JLabel();
        jlblUsuario = new javax.swing.JLabel();
        jmbMenuPrincipal = new javax.swing.JMenuBar();
        jmInventario = new javax.swing.JMenu();
        jmMovimientos = new javax.swing.JMenu();
        jmiMovimientoEntrada = new javax.swing.JMenuItem();
        jmiMovimientoSalida = new javax.swing.JMenuItem();
        jmiMovimientoAsignarCheque = new javax.swing.JMenuItem();
        jmProductos = new javax.swing.JMenu();
        jmiProductoConsultar = new javax.swing.JMenuItem();
        jmiproductoBajoStock = new javax.swing.JMenuItem();
        jmProveedores = new javax.swing.JMenu();
        jmiProveedorNuevo = new javax.swing.JMenuItem();
        jmiProveedorModificar = new javax.swing.JMenuItem();
        jmReportes = new javax.swing.JMenu();
        jmAdministracion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Inventario - Fundación María");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));

        jpnlFondo.setAlignmentX(0.0F);
        jpnlFondo.setAlignmentY(0.0F);
        jpnlFondo.setImagen("/Imagenes/Background.jpg");

        jpnlBarraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jpnlBarraEstado.setAlignmentX(0.0F);
        jpnlBarraEstado.setAlignmentY(0.0F);

        jlblTituloUsuario.setText("Usuario:");

        jlblUsuario.setText("Texto");

        javax.swing.GroupLayout jpnlBarraEstadoLayout = new javax.swing.GroupLayout(jpnlBarraEstado);
        jpnlBarraEstado.setLayout(jpnlBarraEstadoLayout);
        jpnlBarraEstadoLayout.setHorizontalGroup(
            jpnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBarraEstadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlblTituloUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(347, Short.MAX_VALUE))
        );
        jpnlBarraEstadoLayout.setVerticalGroup(
            jpnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBarraEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jlblTituloUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnlFondoLayout = new javax.swing.GroupLayout(jpnlFondo);
        jpnlFondo.setLayout(jpnlFondoLayout);
        jpnlFondoLayout.setHorizontalGroup(
            jpnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBarraEstado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnlFondoLayout.setVerticalGroup(
            jpnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnlFondoLayout.createSequentialGroup()
                .addGap(0, 508, Short.MAX_VALUE)
                .addComponent(jpnlBarraEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jmInventario.setText("Inventario");

        jmMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMovimiento32x32.png"))); // NOI18N
        jmMovimientos.setText("Movimientos");

        jmiMovimientoEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnEntrada32x32.png"))); // NOI18N
        jmiMovimientoEntrada.setText("Entrada");
        jmiMovimientoEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovimientoEntradaActionPerformed(evt);
            }
        });
        jmMovimientos.add(jmiMovimientoEntrada);

        jmiMovimientoSalida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnSalida32x32.png"))); // NOI18N
        jmiMovimientoSalida.setText("Salida");
        jmiMovimientoSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovimientoSalidaActionPerformed(evt);
            }
        });
        jmMovimientos.add(jmiMovimientoSalida);

        jmiMovimientoAsignarCheque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnCheque32x32.png"))); // NOI18N
        jmiMovimientoAsignarCheque.setText("Asignar Cheque");
        jmiMovimientoAsignarCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiMovimientoAsignarChequeActionPerformed(evt);
            }
        });
        jmMovimientos.add(jmiMovimientoAsignarCheque);

        jmInventario.add(jmMovimientos);

        jmProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnProductos32x32.png"))); // NOI18N
        jmProductos.setText("Productos");

        jmiProductoConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnMantenimientoProductos32x32.png"))); // NOI18N
        jmiProductoConsultar.setText("Consultar");
        jmiProductoConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProductoConsultarActionPerformed(evt);
            }
        });
        jmProductos.add(jmiProductoConsultar);

        jmiproductoBajoStock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/btnBajoStock32x32.png"))); // NOI18N
        jmiproductoBajoStock.setText("Bajo Stock");
        jmiproductoBajoStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiproductoBajoStockActionPerformed(evt);
            }
        });
        jmProductos.add(jmiproductoBajoStock);

        jmInventario.add(jmProductos);

        jmProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Proveedores32x32.png"))); // NOI18N
        jmProveedores.setText("Proveedores");

        jmiProveedorNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/NuevoProveedor32x32.png"))); // NOI18N
        jmiProveedorNuevo.setText("Nuevo");
        jmiProveedorNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedorNuevoActionPerformed(evt);
            }
        });
        jmProveedores.add(jmiProveedorNuevo);

        jmiProveedorModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ModificarProveedor32x32.png"))); // NOI18N
        jmiProveedorModificar.setText("Modificar");
        jmiProveedorModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProveedorModificarActionPerformed(evt);
            }
        });
        jmProveedores.add(jmiProveedorModificar);

        jmInventario.add(jmProveedores);

        jmbMenuPrincipal.add(jmInventario);

        jmReportes.setText("Reportes");
        jmbMenuPrincipal.add(jmReportes);

        jmAdministracion.setText("Administración");
        jmbMenuPrincipal.add(jmAdministracion);

        setJMenuBar(jmbMenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiMovimientoEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovimientoEntradaActionPerformed
        JdlgMovimientoEntrada ventanaMovimientoEntrada = new JdlgMovimientoEntrada(this, true);
        ventanaMovimientoEntrada.setVisible(true);
    }//GEN-LAST:event_jmiMovimientoEntradaActionPerformed

    private void jmiMovimientoSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovimientoSalidaActionPerformed
        JdlgMovimientoSalida ventanaMovimientoSalida = new JdlgMovimientoSalida(this, true);
        ventanaMovimientoSalida.setVisible(true);
    }//GEN-LAST:event_jmiMovimientoSalidaActionPerformed

    private void jmiProductoConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProductoConsultarActionPerformed
        JdlgConsultarModificarProducto ventanaConsultarProducto = new JdlgConsultarModificarProducto(this, true);
        ventanaConsultarProducto.setVisible(true);
    }//GEN-LAST:event_jmiProductoConsultarActionPerformed

    private void jmiproductoBajoStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiproductoBajoStockActionPerformed
        JdlgBajoStock ventanaBajoStock = new JdlgBajoStock(this, true);
        ventanaBajoStock.setVisible(true);
    }//GEN-LAST:event_jmiproductoBajoStockActionPerformed

    private void jmiProveedorNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedorNuevoActionPerformed
        JdlgNuevoProveedor ventanaNuevoProveedor = new JdlgNuevoProveedor(this, true);
        ventanaNuevoProveedor.setVisible(true);
    }//GEN-LAST:event_jmiProveedorNuevoActionPerformed

    private void jmiProveedorModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProveedorModificarActionPerformed
        JdlgModificarProveedor ventanaModificarProveedor = new JdlgModificarProveedor(this, true);
        ventanaModificarProveedor.setVisible(true);
    }//GEN-LAST:event_jmiProveedorModificarActionPerformed

    private void jmiMovimientoAsignarChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiMovimientoAsignarChequeActionPerformed
        JdlgAsignarCheque ventanaAsignarCheque = new JdlgAsignarCheque(this, true, usuarioActual.getUsuario());
        ventanaAsignarCheque.setVisible(true);
    }//GEN-LAST:event_jmiMovimientoAsignarChequeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JfrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JfrmPrincipal(new Usuario()).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlblTituloUsuario;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmInventario;
    private javax.swing.JMenu jmMovimientos;
    private javax.swing.JMenu jmProductos;
    private javax.swing.JMenu jmProveedores;
    private javax.swing.JMenu jmReportes;
    private javax.swing.JMenuBar jmbMenuPrincipal;
    private javax.swing.JMenuItem jmiMovimientoAsignarCheque;
    private javax.swing.JMenuItem jmiMovimientoEntrada;
    private javax.swing.JMenuItem jmiMovimientoSalida;
    private javax.swing.JMenuItem jmiProductoConsultar;
    private javax.swing.JMenuItem jmiProveedorModificar;
    private javax.swing.JMenuItem jmiProveedorNuevo;
    private javax.swing.JMenuItem jmiproductoBajoStock;
    private javax.swing.JPanel jpnlBarraEstado;
    private VistaJPanelConFondo.JPanelConFondo jpnlFondo;
    // End of variables declaration//GEN-END:variables
}
